version: "3.8"

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: "docker"
      POSTGRESQL_PASSWORD: "docker"
      POSTGRESQL_DATABASE: "nest-clean"
